name: Check workflow files

on:
  pull_request:
    paths:
      - .github/workflows/*
      - .github/actions/*
      - aqua.yaml

jobs:
  check-workflow-files:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setting up aqua
        uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.51.2

      - name: Run actionlint
        run: actionlint

      - name: Run ghalint
        run: |
          ghalint run
          ghalint run-action
